version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    ports:
    - "8000:80"

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    tty: true
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: we_permit_reg
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
    - ./data:/var/lib/mysql
    ports:
      - "3306:3306"

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"

  npm:
    build:
      context: .
      dockerfile: npm.dockerfile
    container_name: npm
    volumes:
      - ./src:/var/www/html

  composer:
    image: composer
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    command: composer --version

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: artisan
    depends_on:
      - mysql
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']










